---
defaults: &defaults
  docker:
    - image: gcr.io/planet-4-151612/circleci-base:latest
  working_directory: /home/circleci/app

version: 2

jobs:
  deploy-tag:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    steps:
      - run: trigger-build-api.sh planet4-styleguide-deploy master

  deploy-dev:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: activate-gcloud-account.sh
      - run: docker-login.sh
      - run: cd /home/circleci/app/deploy
      - run: make checkout-develop
      - run: make build
      - run: make docker-push
      - run: make dev


workflows:
  version: 2
  dev:
    jobs:
      - deploy-dev:
          context: org-global
          filters:
            branches:
              only: deploy
  tag:
    jobs:
      - deploy-tag:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
